### ISSUE TITLE
image2vec.py fails with "ValueError: setting an array element with a sequence."

### ISSUE THREAD

**Issue by n0531m** [groovenauts/QueryItSmart#89]
execution of image2vec.py fails with the following message:

```
INFO:tensorflow:VGG-16 models for 100 images
INFO:tensorflow:07:43:25
Traceback (most recent call last):
  File "vgg16_vectorize/image2vec.py", line 57, in <module>
    v1, v2 = sess.run([row, prob], feed_dict={ x: imgs, 'vgg16/dropout_1/random_uniform:0': [[1.0]*4096], 'vgg16/dropout/random_uniform:0': [[1.0]*4096]})
  File "/Users/foo/work/queryit/ve_queryit/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/foo/work/queryit/ve_queryit/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1093, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/Users/foo/work/queryit/ve_queryit/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by leeyamkeng** [comment]
Me too. I have encountered same issue. Is there any way to solve it?

**Comment by leeyamkeng** [comment]
Gotcha! Please try to resize the original images into ones with 224*224 dimension.
It works for me, then.

**Comment by nagachika** [comment]
I'm sorry @n0531m for my too late reaction. I overlook  this issue.

And thank you @leeyamkeng for ping me. You are right.
As mentioned in [README](https://github.com/groovenauts/QueryItSmart/tree/master/models#vgg16-vectorize), the images to vectorized with `vgg16_vectorize/image2vec.py` should be in JPEG format and cropped/resized into 224x224 pixels.
